version: '3'

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./requirements/nginx
    networks:
      - inception
    volumes:
      - wordpress-data:/var/www/html
    ports:
      - "443:443"

  mariadb:
    container_name: mariadb
    restart: always
    build:
      context: ./requirements/mariadb
      args:
        SQL_DATABASE: ${SQL_DATABASE}
        SQL_USER: ${SQL_USER}
        SQL_PASSWORD: ${SQL_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h localhost -u root
      interval: 1s
      timeout: 1s
      retries: 5
    networks:
      - inception
    env_file: ./.env
    volumes:
      - mariadb-data:/var/lib/mysql

  wordpress:
    container_name: wordpress
    restart: always
    build:
      context: ./requirements/wordpress
    environment:
      - SQL_DATABASE=${SQL_DATABASE}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${SQL_PASSWORD}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_USER=${WP_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - inception
    env_file: ./.env
    volumes:
      - wordpress-data:/var/www/html

volumes:
  wordpress-data:
    name: wordpress-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/lucade-s/data/wordpress/

  mariadb-data:
    name: mariadb-data
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/lucade-s/data/mariadb/