# Generated by Django 5.1.3 on 2024-12-19 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("status", models.IntegerField(default=0)),
                ("created_by", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("roomId", models.CharField(max_length=64)),
                ("isSinglePlayer", models.BooleanField(default=False)),
                ("matchId", models.CharField(max_length=64)),
            ],
            options={
                "db_table": "Games",
            },
        ),
        migrations.CreateModel(
            name="PlayerModel",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_connected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("color", models.CharField(max_length=64)),
                ("score", models.IntegerField(default=0)),
                ("win", models.IntegerField(default=0)),
                ("name", models.CharField(default="Anonymous", max_length=100)),
                (
                    "gameId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="games_app.gamemodel",
                    ),
                ),
            ],
            options={
                "db_table": "Players",
            },
        ),
        migrations.CreateModel(
            name="ScoreModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gameId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="games_app.gamemodel",
                    ),
                ),
                (
                    "playerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="games_app.playermodel",
                    ),
                ),
            ],
            options={
                "db_table": "Scores",
                "indexes": [
                    models.Index(
                        fields=["gameId", "playerId"], name="Scores_gameId__b2f86e_idx"
                    )
                ],
                "unique_together": {("gameId", "playerId")},
            },
        ),
    ]
