# Generated by Django 5.1.3 on 2024-12-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamemodel",
            name="stage",
            field=models.IntegerField(default=1),
        ),
    ]
