# Generated by Django 5.1.2 on 2024-11-24 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamemodel",
            old_name="roomId",
            new_name="room",
        ),
    ]
