# Generated by Django 5.1.2 on 2024-12-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_rename_roomid_gamemodel_room"),
        ("players", "0007_remove_player_gameid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GameModel",
        ),
    ]
