# Generated by Django 5.1.2 on 2024-11-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="amountOfPlayers",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Creating Room"),
                    (1, "Room Created"),
                    (2, "Waiting Minimal Amount of Players"),
                    (3, "Ready for Start"),
                    (4, "Creating Game"),
                    (5, "Game Created"),
                    (6, "Game Started"),
                    (7, "Game Ended"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.IntegerField(
                choices=[(0, "Match"), (1, "Tournament")], default=0
            ),
        ),
    ]
