# Generated by Django 5.1.2 on 2024-12-16 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0002_alter_room_amountofplayers_alter_room_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                ("gameId", models.CharField(editable=False, max_length=64, null=True)),
                ("stage", models.IntegerField(default=1)),
                ("winner", models.CharField(editable=False, max_length=64, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[(0, "created"), (1, "in progress"), (2, "finished")],
                        default="created",
                        max_length=14,
                    ),
                ),
                ("createdBy", models.CharField(max_length=64)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedBy", models.CharField(max_length=64)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchs",
                        to="rooms.room",
                    ),
                ),
            ],
        ),
    ]
