# Generated by Django 5.1.2 on 2024-12-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Creating Room"),
                    (1, "Room Created"),
                    (2, "Waiting Minimal Amount of Players"),
                    (3, "Ready for Start"),
                    (4, "Creating Game"),
                    (5, "Game Created"),
                    (6, "Game Started"),
                    (7, "Game Ended"),
                    (10, "Tournament Created"),
                    (11, "Tournament Started"),
                    (12, "Tournament In Progress"),
                    (13, "Tournament Ended"),
                ],
                default=0,
            ),
        ),
    ]
