# Generated by Django 5.1.2 on 2024-12-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0005_match_nextmatch_match_position_alter_match_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="stage",
            field=models.IntegerField(default=1),
        ),
    ]
