# Generated by Django 5.1.2 on 2024-11-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_player_profilecolor"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
