# Generated by Django 5.1.2 on 2024-11-23 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0002_alter_player_profilecolor"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="roomId",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="rooms.room",
            ),
            preserve_default=False,
        ),
    ]
