# Generated by Django 5.1.2 on 2024-11-24 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0003_player_roomid"),
        ("players", "0003_player_score"),
    ]

    operations = []
