# Generated by Django 5.1.2 on 2024-12-12 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("games", "0002_rename_roomid_gamemodel_room"),
        ("players", "0004_merge_0003_player_roomid_0003_player_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="GameId",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="games.gamemodel",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="bracketsPosition",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="isConnected",
            field=models.BooleanField(default=False),
        ),
    ]
