# Generated by Django 5.1.2 on 2024-12-19 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0007_remove_player_gameid"),
        ("rooms", "0005_match_nextmatch_match_position_alter_match_status_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="matchplayer",
            unique_together={("match", "player")},
        ),
    ]
