name: build
on: |
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:  006-push-swap
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
